framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  session:
    enabled: true
    cookie_secure: auto
    cookie_httponly: true
    cookie_samesite: strict
  form: true
  serializer:
    enabled: true
  messenger:
    transports:
      sync: 'sync://'
    routing:
      'App\Showcase\Application\Messaging\ShowcaseAuditMessage': sync
  validation:
    enabled: true
