services:
  app:
    container_name: showoff-php-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: ["php", "-S", "0.0.0.0:8080", "-t", "public", "public/index.php"]
